### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [AwesomeOpenSource/awesome-images#13]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by heyalexej** [comment]
![hell-yeah](https://cloud.githubusercontent.com/assets/2575014/7025736/c479e4c2-dd6f-11e4-810c-822129f764e5.jpg)

let's do it!

**Comment by jeffreyjackson** [comment]
cc @dkhamsing

@heyalexej you can make the transfer here: https://github.com/heyalexej/awesome-images/settings#transfer_confirm

**Comment by heyalexej** [comment]
never did this before. reading up on it so i don't mess it up ;)

**Comment by jeffreyjackson** [comment]
sure no problem

**Comment by heyalexej** [comment]
so, will you add me to the org so i can co-maintain it further or how does it work?

**Comment by jeffreyjackson** [comment]
you will want to transfer it to AwesomeOpenSource, and I have added you as an admin to the organization.

navigate to github.com/AwesomeOpenSource and accept the invite

**Comment by heyalexej** [comment]
done. will read up on how maintenance works within orgs etc. good point in time to learn it.

**Comment by dkhamsing** [comment]
:tada:

**Comment by jeffreyjackson** [comment]
I feel like this is the beginning of something really awesome :smiley:
